package fr.utbm.lo54.project.projectLo54.core.entity;
// Generated 1 avr. 2016 17:55:23 by Hibernate Tools 4.3.1



/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private int id;
     private String lastName;
     private String firstName;
     private String address;
     private String phone;
     private String email;
     private Integer courseSessionId;

    public Client() {
    }

	
    public Client(int id, String lastName, String firstName, String address, String phone) {
        this.id = id;
        this.lastName = lastName;
        this.firstName = firstName;
        this.address = address;
        this.phone = phone;
    }
    public Client(int id, String lastName, String firstName, String address, String phone, String email, Integer courseSessionId) {
       this.id = id;
       this.lastName = lastName;
       this.firstName = firstName;
       this.address = address;
       this.phone = phone;
       this.email = email;
       this.courseSessionId = courseSessionId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getCourseSessionId() {
        return this.courseSessionId;
    }
    
    public void setCourseSessionId(Integer courseSessionId) {
        this.courseSessionId = courseSessionId;
    }




}


