package fr.utbm.lo54.project.core.entity;

import java.io.Serializable;

/**
 * Client generated by hbm2java
 */
public class Client  implements Serializable, IEntity {

     private int id;
     private String lastName;
     private String firstName;
     private String address;
     private String phone;
     private String email;
     private int courseSessionId;

    public Client() {
    }

	
    public Client(int id, String lastName, String firstName, String address, String phone) {
        this.id = id;
        this.lastName = lastName;
        this.firstName = firstName;
        this.address = address;
        this.phone = phone;
    }
    public Client(int id, String lastName, String firstName, String address, String phone, String email, int courseSessionId) {
       this.id = id;
       this.lastName = lastName;
       this.firstName = firstName;
       this.address = address;
       this.phone = phone;
       this.email = email;
       this.courseSessionId = courseSessionId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getCourseSessionId() {
        return this.courseSessionId;
    }
    
    public void setCourseSessionId(int courseSessionId) {
        this.courseSessionId = courseSessionId;
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("Client{");
        builder.append("id=" + id);
        builder.append(", lastName=" + lastName);
        builder.append(", firstName=" + firstName);
        builder.append(", address=" + address);
        builder.append(", phone=" + phone);
        builder.append(", email=" + email);
        //builder.append(", courseSessionId=" + courseSessionId);
        return builder.toString();
    }
    
    

}
