package fr.utbm.lo54.project.core.entity;

/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {

     private int id;
     private String city;

    public Location() {
    }

    public Location(int id, String city) {
       this.id = id;
       this.city = city;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

}


