package fr.utbm.lo54.project.project_lo54.test;
// Generated 1 avr. 2016 17:55:23 by Hibernate Tools 4.3.1



/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private int id;
     private String city;

    public Location() {
    }

    public Location(int id, String city) {
       this.id = id;
       this.city = city;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }




}


